<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>qr_homage app</name>
   <tag></tag>
   <elementGuidId>ca136b19-4ced-4448-aa18-847ad01553be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='page_template_1']/main/section</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>section.download-app</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>section</value>
      <webElementGuid>00b18317-cbc8-4cc1-b2db-cbac92ced487</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>download-app</value>
      <webElementGuid>15cd9db3-9e81-4df3-b60f-26d010fbbf6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Download the Homage appScan the QR code to download the app  ORClick on the button to download the app 4.7 mobile rating</value>
      <webElementGuid>b08b0fed-f86f-4c93-a90f-63fc7e2ef9ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page_template_1&quot;)/main[1]/section[@class=&quot;download-app&quot;]</value>
      <webElementGuid>41362992-f855-470a-a0cb-bbdd5c22ac53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='page_template_1']/main/section</value>
      <webElementGuid>ff92ccf6-9962-4aa8-b595-946e41e9f2ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This field is for validation purposes and should be left unchanged.'])[1]/following::section[1]</value>
      <webElementGuid>ec02effe-a0f7-44a2-92e7-03034e9ed8d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone'])[1]/following::section[1]</value>
      <webElementGuid>b99a1b39-0233-4c17-9db1-e915d22a2826</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About'])[2]/preceding::section[1]</value>
      <webElementGuid>016f8821-9ecb-491e-a8a9-e42f99b95f6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/section</value>
      <webElementGuid>e1ae3e2a-4ace-4c46-8fde-4ac0186b56bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//section[(text() = 'Download the Homage appScan the QR code to download the app  ORClick on the button to download the app 4.7 mobile rating' or . = 'Download the Homage appScan the QR code to download the app  ORClick on the button to download the app 4.7 mobile rating')]</value>
      <webElementGuid>f5166368-86f8-42a1-828a-0dc98d5f9c87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
