<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>section_Medical Conditions</name>
   <tag></tag>
   <elementGuidId>e4913947-c8c3-44d5-b0c6-2c5ffed0d9d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='page_template_1']/main/section[7]/div/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fdbac3a8-f526-4762-99a6-88734e92f9dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-12</value>
      <webElementGuid>2b1f78f2-4186-4b95-a440-3bc5866375a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Medical Conditions    Dementia   Diabetes   Hypertension   Stroke   Cancer   Parkinson's   Reasons of Engagement    Respite Care for Caregiver   Stay in care   Relief/Supplement helper   Medicine Delivery   Companionship   Post Hospital Discharge </value>
      <webElementGuid>6af1d3fe-e327-4420-8cc6-5914a81c787b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page_template_1&quot;)/main[1]/section[@class=&quot;chronicConditions&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12&quot;]</value>
      <webElementGuid>84b75160-bafb-492d-9253-dc86c35817bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='page_template_1']/main/section[7]/div/div/div[2]</value>
      <webElementGuid>3a86acfe-d96e-487d-94fa-3724bc8ab1f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Only the best care for you and your loved ones'])[1]/following::div[1]</value>
      <webElementGuid>71bc7568-65d0-4a71-b9cf-142959f5be42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Care Reporting'])[1]/following::div[6]</value>
      <webElementGuid>36b2020c-c017-4b29-91f7-b5b2e6a1b2d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[7]/div/div/div[2]</value>
      <webElementGuid>68a1a1f8-534c-48e1-9182-c1ea52c2defe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot;  Medical Conditions    Dementia   Diabetes   Hypertension   Stroke   Cancer   Parkinson&quot; , &quot;'&quot; , &quot;s   Reasons of Engagement    Respite Care for Caregiver   Stay in care   Relief/Supplement helper   Medicine Delivery   Companionship   Post Hospital Discharge &quot;) or . = concat(&quot;  Medical Conditions    Dementia   Diabetes   Hypertension   Stroke   Cancer   Parkinson&quot; , &quot;'&quot; , &quot;s   Reasons of Engagement    Respite Care for Caregiver   Stay in care   Relief/Supplement helper   Medicine Delivery   Companionship   Post Hospital Discharge &quot;))]</value>
      <webElementGuid>d4d8e054-ec85-424e-bd00-ffaedc38ebc4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
