<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>section_Our Services</name>
   <tag></tag>
   <elementGuidId>13a0cf9b-b6c1-4788-a4e0-55c888dc1895</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='page_template_1']/main/section[4]/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>section.services > div.container-fluid > div.row > div.col-12</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>627b013c-a0e1-40b1-93fa-4e0ee689321f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-12</value>
      <webElementGuid>9be7ce8d-d8fe-4c1e-a45a-a83c6e5a97cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Our Services    Home Personal Care     Home Nursing     Home Therapy     Home Medical     Tele-Consultation     Medicine Delivery  Home Personal Care Our trained local caregivers assist with you and your loved one’s activities of daily living (ADLs) for safe and independent living at home. This includes eating, bathing, getting dressed, toileting, transferring and continence. Elderly Care Respite Care Caregivers Part-Time Caregivers Medical Escort Home Nursing Our licensed local nurses can save you and your loved ones a trip to the clinic and hospital. Get simple and complex nursing procedures such as tube, stoma and wound care in the comfort of your home. Private Nurses IV Drip Stoma Care Wound Care Medical Administration Tube Change Catheter Care Home Therapy Our experienced local therapists are here to support your rehabilitation and recovery efforts when you return home, through personalised exercise and therapy treatment sessions. Physiotherapy Occupational Therapy Speech Therapy Home Medical Sick or experiencing discomfort? Have a loved one who is feeling unwell but is immobile or unwilling to visit the clinic? Our team of local licensed doctors at Homage are here to respond to you or your loved one 24/7. House Call Doctors General Practitioners Health Screening Simple Surgical Procedures Private Ambulance Tele-Consultation Our team of local licensed doctors at Homage are available to attend to your medical needs through a video call 24/7, anywhere in Singapore. Online Doctors General Practitioners Medical Certificate Medicine Delivery Save the hassle, cost and time of travelling to and fro home and pharmacies. Your medication will be delivered to your doorstep on the same day post-consultation with our doctors. House Call Doctors Online Doctors      </value>
      <webElementGuid>fe8dfe83-2996-4ab0-9223-1a6d1f5a4704</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page_template_1&quot;)/main[1]/section[@class=&quot;services&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12&quot;]</value>
      <webElementGuid>c494cc96-786a-4102-a53c-c259e1ee9660</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='page_template_1']/main/section[4]/div/div/div</value>
      <webElementGuid>452956dc-deeb-4619-a011-9d24903910c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Corporates'])[4]/following::div[3]</value>
      <webElementGuid>1447d25d-a4a2-478c-a28e-2782f02a1c2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Government Organisations'])[3]/following::div[5]</value>
      <webElementGuid>1fb71fdb-ac9c-497b-9547-6345f4681ab5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[4]/div/div/div</value>
      <webElementGuid>122fca7f-6a60-428d-b30a-eadec07d0e3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Our Services    Home Personal Care     Home Nursing     Home Therapy     Home Medical     Tele-Consultation     Medicine Delivery  Home Personal Care Our trained local caregivers assist with you and your loved one’s activities of daily living (ADLs) for safe and independent living at home. This includes eating, bathing, getting dressed, toileting, transferring and continence. Elderly Care Respite Care Caregivers Part-Time Caregivers Medical Escort Home Nursing Our licensed local nurses can save you and your loved ones a trip to the clinic and hospital. Get simple and complex nursing procedures such as tube, stoma and wound care in the comfort of your home. Private Nurses IV Drip Stoma Care Wound Care Medical Administration Tube Change Catheter Care Home Therapy Our experienced local therapists are here to support your rehabilitation and recovery efforts when you return home, through personalised exercise and therapy treatment sessions. Physiotherapy Occupational Therapy Speech Therapy Home Medical Sick or experiencing discomfort? Have a loved one who is feeling unwell but is immobile or unwilling to visit the clinic? Our team of local licensed doctors at Homage are here to respond to you or your loved one 24/7. House Call Doctors General Practitioners Health Screening Simple Surgical Procedures Private Ambulance Tele-Consultation Our team of local licensed doctors at Homage are available to attend to your medical needs through a video call 24/7, anywhere in Singapore. Online Doctors General Practitioners Medical Certificate Medicine Delivery Save the hassle, cost and time of travelling to and fro home and pharmacies. Your medication will be delivered to your doorstep on the same day post-consultation with our doctors. House Call Doctors Online Doctors      ' or . = 'Our Services    Home Personal Care     Home Nursing     Home Therapy     Home Medical     Tele-Consultation     Medicine Delivery  Home Personal Care Our trained local caregivers assist with you and your loved one’s activities of daily living (ADLs) for safe and independent living at home. This includes eating, bathing, getting dressed, toileting, transferring and continence. Elderly Care Respite Care Caregivers Part-Time Caregivers Medical Escort Home Nursing Our licensed local nurses can save you and your loved ones a trip to the clinic and hospital. Get simple and complex nursing procedures such as tube, stoma and wound care in the comfort of your home. Private Nurses IV Drip Stoma Care Wound Care Medical Administration Tube Change Catheter Care Home Therapy Our experienced local therapists are here to support your rehabilitation and recovery efforts when you return home, through personalised exercise and therapy treatment sessions. Physiotherapy Occupational Therapy Speech Therapy Home Medical Sick or experiencing discomfort? Have a loved one who is feeling unwell but is immobile or unwilling to visit the clinic? Our team of local licensed doctors at Homage are here to respond to you or your loved one 24/7. House Call Doctors General Practitioners Health Screening Simple Surgical Procedures Private Ambulance Tele-Consultation Our team of local licensed doctors at Homage are available to attend to your medical needs through a video call 24/7, anywhere in Singapore. Online Doctors General Practitioners Medical Certificate Medicine Delivery Save the hassle, cost and time of travelling to and fro home and pharmacies. Your medication will be delivered to your doorstep on the same day post-consultation with our doctors. House Call Doctors Online Doctors      ')]</value>
      <webElementGuid>b8888f73-4009-4b83-951a-ee5f9386553c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
