<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>title_Homage app page</name>
   <tag></tag>
   <elementGuidId>f4520161-2a22-4816-a2dd-67041d5a5ef9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-38329']/section/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8d8e66a1-4fef-49d5-9a16-b14379b1fe48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>heroContent </value>
      <webElementGuid>c31866d1-008c-4196-8aa5-5447199a5d05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Home Care On DemandWith the Homage mobile app, request and manage care for you and your loved ones wherever, whenever. Whether you need personal care, nursing services, domestic support or community participation access, help is just a few taps away.Download the Homage App  </value>
      <webElementGuid>8066c155-191c-4f33-a057-e47d8e723f1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-38329&quot;)/section[@class=&quot;heroBanner&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xl-5 col-lg-6 heroContent__container&quot;]/div[@class=&quot;heroContent&quot;]</value>
      <webElementGuid>76573ace-2969-4de5-9ccf-72a75602a88e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-38329']/section/div/div/div/div</value>
      <webElementGuid>6c0d6298-39f2-48ba-b327-0f8bf4ddfd67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Australia'])[2]/following::div[5]</value>
      <webElementGuid>1c23472d-51d9-4a5e-8201-3144777f821d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Malaysia'])[2]/following::div[5]</value>
      <webElementGuid>e560a546-a9d5-4650-9f4c-78cd73e78730</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Why use the app?'])[1]/preceding::div[6]</value>
      <webElementGuid>57641a20-a9b4-468a-acbf-d21f9222bab3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div/div</value>
      <webElementGuid>99912a02-894b-4410-b3b5-5235dd3a4187</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Home Care On DemandWith the Homage mobile app, request and manage care for you and your loved ones wherever, whenever. Whether you need personal care, nursing services, domestic support or community participation access, help is just a few taps away.Download the Homage App  ' or . = 'Home Care On DemandWith the Homage mobile app, request and manage care for you and your loved ones wherever, whenever. Whether you need personal care, nursing services, domestic support or community participation access, help is just a few taps away.Download the Homage App  ')]</value>
      <webElementGuid>87a54362-6657-4ef4-be7c-742d391c4974</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
