<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Delivery</name>
   <tag></tag>
   <elementGuidId>cbe98b83-d07f-49ce-b78e-1d8af4ce8492</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@href = '/help-center/delivery' and (text() = ' 
            Delivery
          ' or . = ' 
            Delivery
          ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.sub-section__list</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1359c26c-51cc-4e31-8875-9fc71d8b96bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/help-center/delivery</value>
      <webElementGuid>a913516a-9cab-450d-8ad4-d165160f4eff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sub-section__list</value>
      <webElementGuid>2567b98b-16b3-4665-a0b7-6f9ad73cff0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 
            Delivery
          </value>
      <webElementGuid>6fdfbddf-980e-42d1-8055-8cf8eab87beb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;help-center&quot;]/section[@class=&quot;help-center__body&quot;]/div[@class=&quot;section__container help-center__body-container&quot;]/div[@class=&quot;help-center-index help-center__body-child&quot;]/div[@class=&quot;product&quot;]/div[@class=&quot;product__list&quot;]/div[@class=&quot;sub-section sub-section--active&quot;]/a[@class=&quot;sub-section__list&quot;]</value>
      <webElementGuid>883542c5-a2e9-44ff-a0d6-9b7cebe39d69</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/section[2]/div/div[2]/div/div/div[2]/a</value>
      <webElementGuid>f6c11855-d241-457f-83bb-111ecffba9c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daily'])[1]/following::a[1]</value>
      <webElementGuid>5d27695e-770b-4ba2-839f-c88af760f326</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Semua Layanan'])[1]/following::a[1]</value>
      <webElementGuid>fa739f43-891f-4911-808e-8ecde2d4ae23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loyalti'])[1]/preceding::a[1]</value>
      <webElementGuid>89021703-ccfc-4521-ac2e-a8e026d650e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/help-center/delivery')]</value>
      <webElementGuid>1f16ca0d-c5f2-4315-8b9b-228df6f10e00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/a</value>
      <webElementGuid>72b89b42-c8c4-4b1b-81ac-2b659aa9ab77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/help-center/delivery' and (text() = ' 
            Delivery
          ' or . = ' 
            Delivery
          ')]</value>
      <webElementGuid>45e77708-dd06-435f-b4e9-8ddd29780533</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
