<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_redirectYoutube</name>
   <tag></tag>
   <elementGuidId>ea8de038-ade8-4ca4-9707-38e99f533de7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@src = 'https://a.m.dana.id/resource/icons/youtube.png' and @alt = 'youtube']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;youtube&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>cb0df891-5650-4755-bacd-d9d4627618c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://a.m.dana.id/resource/icons/youtube.png</value>
      <webElementGuid>b4db8995-b7ed-4f12-ba39-50dd3a2ccdc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>youtube</value>
      <webElementGuid>5d3e6c08-aec9-4971-a9cc-c641ce29e739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;item-digital&quot;]/div[@class=&quot;footer&quot;]/div[@class=&quot;footer__bottom f-flex f-justify-space-between f-align-center pt-20&quot;]/div[@class=&quot;footer__bottom__right&quot;]/a[4]/img[1]</value>
      <webElementGuid>c370992f-2b60-45cf-a709-f43445816eae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[3]/div[2]/div/a[4]/img</value>
      <webElementGuid>e30f1bec-b6e7-406a-8c1f-0acb159a784c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='youtube']</value>
      <webElementGuid>93ecba6e-875f-419d-b8c6-263bab4b2aaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]/img</value>
      <webElementGuid>0df29599-722d-465a-b159-16979c47ff29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://a.m.dana.id/resource/icons/youtube.png' and @alt = 'youtube']</value>
      <webElementGuid>ed7451ca-d200-4b11-8083-09c020b2ae8f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
