<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_CANCEL</name>
   <tag></tag>
   <elementGuidId>78aae18a-e92f-4999-add4-ade0f18c407d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.f-btn.f-btn-ghost.f-btn-smallFixed</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2e01d480-42cc-4019-92b7-d6c177f2b3a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d1a8b56c-44c4-4f50-92ce-8b74fbeeac22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>f-btn f-btn-ghost f-btn-smallFixed</value>
      <webElementGuid>30be956a-883d-44b5-9098-c17824bf9248</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
        CANCEL
      </value>
      <webElementGuid>12e4b4a5-e5e7-4192-aedd-c60fb28f3c4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;item-digital&quot;]/div[@class=&quot;item-digital-home&quot;]/div[@class=&quot;f-dialog add-to-home-popup transformed-dialog&quot;]/div[@class=&quot;f-dialog__container f-dialog__container--modal&quot;]/div[@class=&quot;f-dialog__container__inner&quot;]/div[@class=&quot;f-card&quot;]/div[@class=&quot;f-card__actions px-16 pb-16&quot;]/button[@class=&quot;f-btn f-btn-ghost f-btn-smallFixed&quot;]</value>
      <webElementGuid>ea8f3428-9c2a-4f46-a6d0-6a0deb85c6b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[5]</value>
      <webElementGuid>5be2d410-c49c-4e16-a175-1d89bf557319</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[3]/div[2]/div/div/div[2]/button</value>
      <webElementGuid>ebd6f289-dfa0-4f82-8f41-aee00365c1ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Let', &quot;'&quot;, 's buy game items quickly by opening the shortcut from your home screen!')])[1]/following::button[1]</value>
      <webElementGuid>c03e4fac-aa12-4cd7-b622-a07eb2433872</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Games to Home Screen'])[1]/following::button[1]</value>
      <webElementGuid>ece252ba-dca1-4ac7-9182-ee623ae88d65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADD'])[1]/preceding::button[1]</value>
      <webElementGuid>b763d7c9-b948-447d-8c2c-5bc83f8d56c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Top Up Games'])[1]/preceding::button[2]</value>
      <webElementGuid>54614ca7-b48b-42e7-bf9f-5053570df63f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CANCEL']/parent::*</value>
      <webElementGuid>24e2c0a8-d45e-4dfd-b0d7-8acd769e8c58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/button</value>
      <webElementGuid>f108c033-7c0c-485c-b25f-344bbc14c784</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '
        CANCEL
      ' or . = '
        CANCEL
      ')]</value>
      <webElementGuid>d73cbaa3-f2d0-490f-b3f0-de290e21e420</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
