<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>section_Deals</name>
   <tag></tag>
   <elementGuidId>04668195-c325-4af9-bcdd-b6f861fc30cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='new']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#new</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>75376e4f-8302-4b4d-b74a-a78839cd54f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>new</value>
      <webElementGuid>ec5cdc85-bd92-4672-93ca-b7f23b31309f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>js-deal dc__listw clearfix</value>
      <webElementGuid>77539c7a-6c2d-4cbe-8d3f-7f84a6217829</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>               Top up e-Money Bisa Dari Aplikasi OVO🎉  OVO                         Nonton Dijamin Hemat di CGV  CGV                        Pake OVO Serba Hemat di Google Play  Google Play                        Beragam Tontonan Seru di Prime Video  AMAZON PRIME VIDEO                        Tagihan cuan pake OVO  OVO                         Hematnya Lunasin Tagihan Pake OVO  OVO                         Belanja Murah Bonus Dianter Ke Rumah  OVO                         Awali Bulan dengan Investasi Untung   OVO          </value>
      <webElementGuid>86434729-6d21-4a42-a59f-35ea00569085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;new&quot;)</value>
      <webElementGuid>8a930f0d-b915-4bd3-9cdd-63c04a7b370f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='new']</value>
      <webElementGuid>73d136ca-cc86-49b5-aaec-6ad93d3c9f69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Temukan berbagai penawaran menarik dan dapatkan keuntungan lainnya dari merchant rekanan OVO.'])[1]/following::div[5]</value>
      <webElementGuid>ee5052bc-5761-480a-ba5b-8e8609d3ff2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deals'])[2]/following::div[6]</value>
      <webElementGuid>ddd95ee7-f212-4bb3-b0fe-f58a44a92c0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[3]/div</value>
      <webElementGuid>50153c6e-3dbe-45a0-ac97-e1a23e1ed769</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'new' and (text() = '               Top up e-Money Bisa Dari Aplikasi OVO🎉  OVO                         Nonton Dijamin Hemat di CGV  CGV                        Pake OVO Serba Hemat di Google Play  Google Play                        Beragam Tontonan Seru di Prime Video  AMAZON PRIME VIDEO                        Tagihan cuan pake OVO  OVO                         Hematnya Lunasin Tagihan Pake OVO  OVO                         Belanja Murah Bonus Dianter Ke Rumah  OVO                         Awali Bulan dengan Investasi Untung   OVO          ' or . = '               Top up e-Money Bisa Dari Aplikasi OVO🎉  OVO                         Nonton Dijamin Hemat di CGV  CGV                        Pake OVO Serba Hemat di Google Play  Google Play                        Beragam Tontonan Seru di Prime Video  AMAZON PRIME VIDEO                        Tagihan cuan pake OVO  OVO                         Hematnya Lunasin Tagihan Pake OVO  OVO                         Belanja Murah Bonus Dianter Ke Rumah  OVO                         Awali Bulan dengan Investasi Untung   OVO          ')]</value>
      <webElementGuid>629af351-1b1a-4470-b604-bf594a43309e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
