<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_playstore</name>
   <tag></tag>
   <elementGuidId>2e9e9f39-f219-4097-913c-3c0f7d165f5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/section/div/div/div/a[2]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a:nth-of-type(2) > img.lazyload.is-loaded</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7de30808-f187-45de-b318-f7f67b4e799f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Download on the App Store</value>
      <webElementGuid>50d764cd-c9ee-420b-8d05-f3e659eb5d27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lazyload is-loaded</value>
      <webElementGuid>fad17c78-99f9-4463-a50f-acf6f1e6ed2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_nuxt/img/download-app-store.abbe87e.png</value>
      <webElementGuid>d57a183f-de07-4960-a52a-216343cc3988</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[1]/section[@class=&quot;download&quot;]/div[@class=&quot;section__container&quot;]/div[@class=&quot;download__text&quot;]/div[@class=&quot;download__button&quot;]/a[2]/img[@class=&quot;lazyload is-loaded&quot;]</value>
      <webElementGuid>10c49667-077d-4bc0-ab65-ed31b480cc29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/section/div/div/div/a[2]/img</value>
      <webElementGuid>5e58cd91-74d9-4e69-b368-00661c7de811</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Download on the App Store']</value>
      <webElementGuid>5ff3ba5f-ff85-4be4-9052-6824807a222d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/a[2]/img</value>
      <webElementGuid>50a49f68-f28d-43f5-9d5c-02189848dbb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Download on the App Store' and @src = '/_nuxt/img/download-app-store.abbe87e.png']</value>
      <webElementGuid>2aaafc36-25f6-404f-b02e-1ea041afc439</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
