<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Download</name>
   <tag></tag>
   <elementGuidId>56219bc5-84fa-456e-83b8-8df4f8617e64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(@href, '/download')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.navbar__menu__download</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3ad468d9-80c1-45da-91aa-4e4c9d63d13d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/download</value>
      <webElementGuid>52a46b3a-8622-40f8-92e5-0d2edf478338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>navbar__menu__download</value>
      <webElementGuid>0acc7a80-8917-4cea-b133-112678143405</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
        Download
      </value>
      <webElementGuid>0f114459-357e-4742-aff3-f83f36e2f586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[1]/nav[@class=&quot;navbar&quot;]/div[@class=&quot;navbar__content&quot;]/div[@class=&quot;navbar__right&quot;]/a[@class=&quot;navbar__menu__download&quot;]</value>
      <webElementGuid>a5ef7b1e-57bc-4d3c-a2cc-806713ff051f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/nav/div/div[4]/a</value>
      <webElementGuid>d5a89ffa-cc83-4f2a-95cb-c248a5b9c4fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Download')]</value>
      <webElementGuid>bfe72aa6-084e-417a-a325-a699b0c730b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ID'])[1]/following::a[1]</value>
      <webElementGuid>739183c0-3bdf-4ea1-a40b-d75b5450d6b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EN'])[1]/following::a[2]</value>
      <webElementGuid>dfa5c508-6e76-4553-ae99-ed633aa932d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Semua transaksi bisa di satu dompet digital'])[1]/preceding::a[1]</value>
      <webElementGuid>fded13d6-03ee-4d01-a1c7-5b5a9893050e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tentang DANA'])[1]/preceding::a[4]</value>
      <webElementGuid>c947d43e-f83f-4dd1-a06f-dcd0f2ee9a79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Download']/parent::*</value>
      <webElementGuid>44e3675b-dab7-4033-8ee1-b56ffa7260d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/download')]</value>
      <webElementGuid>3d9fb61f-f346-408c-bda1-098955bfde59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a</value>
      <webElementGuid>dc0d54f5-d15f-4bde-8266-0874f663ab17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/download' and (text() = '
        Download
      ' or . = '
        Download
      ')]</value>
      <webElementGuid>9271f624-58d8-498d-a7c1-54e37c255d18</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
