<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Karir</name>
   <tag></tag>
   <elementGuidId>f84fc164-10e4-403f-b67c-d5ebf0a21e99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(@href, '/career')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.navbar__menu.nuxt-link-exact-active.nuxt-link-active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5d354408-0560-4464-8e81-c942992089a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/career</value>
      <webElementGuid>90f7fe37-386a-41aa-a283-71baea2cc832</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>navbar__menu nuxt-link-exact-active nuxt-link-active</value>
      <webElementGuid>43eb3370-13cf-47da-a163-717a21df8bfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-current</name>
      <type>Main</type>
      <value>page</value>
      <webElementGuid>06a6df21-0e1d-4da4-9070-66b3d4ddf112</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
        Karir
      </value>
      <webElementGuid>247ef1f5-78ef-42e5-ae51-536965db4e1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[1]/nav[@class=&quot;navbar&quot;]/div[@class=&quot;navbar__content&quot;]/div[@class=&quot;navbar__center&quot;]/a[@class=&quot;navbar__menu nuxt-link-exact-active nuxt-link-active&quot;]</value>
      <webElementGuid>e7306670-fc3e-44d3-9352-62229a3caf02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/nav/div/div[3]/a[3]</value>
      <webElementGuid>158ec574-c1fd-4c9e-b882-49b5f4c975a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Karir')]</value>
      <webElementGuid>76536801-7afa-4bae-96ab-2364fd21f736</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bisnis &amp; Enterprise'])[1]/following::a[1]</value>
      <webElementGuid>e7fcc4f9-e7b0-453f-85a5-8557d7125d73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Produk &amp; Fitur'])[1]/following::a[2]</value>
      <webElementGuid>b29cbbf8-4340-4c01-ae67-1568b15e741e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Promo'])[1]/preceding::a[1]</value>
      <webElementGuid>6829303e-f1de-4950-a77d-2aeede6747ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blog'])[1]/preceding::a[2]</value>
      <webElementGuid>1de49959-fc50-45a3-adaa-33955eb08303</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Karir']/parent::*</value>
      <webElementGuid>bace27ec-b81c-424c-9575-5d815501179a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/career')]</value>
      <webElementGuid>2a3646d3-63c4-4593-974e-d982cbbe6f74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]</value>
      <webElementGuid>dc678d06-501d-460f-bf92-5a075cede63e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/career' and (text() = '
        Karir
      ' or . = '
        Karir
      ')]</value>
      <webElementGuid>c7f899ee-3ef8-4c28-a91b-064e1710a272</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
