<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Promo</name>
   <tag></tag>
   <elementGuidId>f67859f0-1293-4524-8a60-53df76fc6de4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(@href, '/promo')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.navbar__menu.nuxt-link-exact-active.nuxt-link-active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c402b567-e89a-4d04-b128-e3f2c9bb0c9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/promo</value>
      <webElementGuid>fb0b1fa8-14ba-4d48-b8b2-10d8d9fa74fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>navbar__menu nuxt-link-exact-active nuxt-link-active</value>
      <webElementGuid>f1b890f4-18bc-4c58-b554-fae1295059e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-current</name>
      <type>Main</type>
      <value>page</value>
      <webElementGuid>0aee696a-b495-4e82-83c1-5d4f08d47aad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
        Promo
      </value>
      <webElementGuid>4adae659-23de-41cc-8451-b199008b60fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[1]/nav[@class=&quot;navbar&quot;]/div[@class=&quot;navbar__content&quot;]/div[@class=&quot;navbar__center&quot;]/a[@class=&quot;navbar__menu nuxt-link-exact-active nuxt-link-active&quot;]</value>
      <webElementGuid>fb0a79e9-8fd2-484b-92f9-7abf701f6afb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/nav/div/div[3]/a[4]</value>
      <webElementGuid>eca226e1-5889-4e3a-b3cd-3cbbae4fe0a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Promo')]</value>
      <webElementGuid>849b731e-e9eb-432d-9b7f-cab58b8e4ae4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Karir'])[1]/following::a[1]</value>
      <webElementGuid>3ee9f844-8f81-4257-99bf-2e09b67f7fe4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bisnis &amp; Enterprise'])[1]/following::a[2]</value>
      <webElementGuid>37287b4b-4c6f-4ab4-ae4a-0720f7a6b975</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blog'])[1]/preceding::a[1]</value>
      <webElementGuid>c84556e4-76e0-4f11-8b3b-aa2e23831458</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pusat Bantuan'])[1]/preceding::a[2]</value>
      <webElementGuid>c7fb7980-f9f1-411a-b3ce-ac052a26e42f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Promo']/parent::*</value>
      <webElementGuid>d66c47d5-e02e-481a-9b7c-c42733c11603</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/promo')]</value>
      <webElementGuid>cf086f18-2334-4126-bbf6-3b2e96f58809</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]</value>
      <webElementGuid>6ff35fad-f5dc-4f82-8145-24a6157ad3ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/promo' and (text() = '
        Promo
      ' or . = '
        Promo
      ')]</value>
      <webElementGuid>d4f59a88-ace7-409c-a8cd-d4dd1f99f914</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
