<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Identity</name>
   <tag></tag>
   <elementGuidId>bdd43ea4-5d7b-424a-b468-b71ae9ec0feb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/section/div/div[51]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e1af6656-80c6-4d6e-bca3-2a5f6b41dbe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>f-card__content</value>
      <webElementGuid>f30f674c-c294-43bd-90ae-d15794064e54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 
        Identity
      </value>
      <webElementGuid>c647cb2e-5b64-4e51-9f3e-2bcf78070dfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;item-digital&quot;]/div[@class=&quot;item-digital-service f-flex f-flex-column l-desktop&quot;]/section[1]/div[@class=&quot;item-digital-grid desktop-view&quot;]/div[@class=&quot;item-digital-card f-flex f-justify-center desktop-view&quot;]/div[@class=&quot;f-card&quot;]/div[@class=&quot;f-card__content&quot;]</value>
      <webElementGuid>8fa6e2b5-d3e3-4aed-95a6-220256b2fd4e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/section/div/div[51]/div/div</value>
      <webElementGuid>9b30d0df-50f8-49fa-a594-1038983ad026</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AU2 Mobile'])[1]/following::div[3]</value>
      <webElementGuid>7c1f6ce8-0694-4054-9a80-6637738ff499</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sushiroll'])[1]/following::div[8]</value>
      <webElementGuid>8d0df409-1794-4e3a-842c-c962d943c2d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Top Up Games'])[1]/preceding::div[3]</value>
      <webElementGuid>f7bdd46e-1a5a-4540-bd28-726cd40efd33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[51]/div/div</value>
      <webElementGuid>354faf94-57da-4954-871c-b3b5a3caa73d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' 
        Identity
      ' or . = ' 
        Identity
      ')]</value>
      <webElementGuid>98afd2e3-c54b-4b54-b2e4-cc7b3a44c300</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
