<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_carousel_news</name>
   <tag></tag>
   <elementGuidId>d35cec7e-93cc-4fe4-9048-86e4687f4857</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt = 'banner-articler' and @src = 'https://a.m.dana.id/promo/gamespage/Web-Banner-Article-Game.png']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;banner-articler&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e4ee475c-0dd0-435b-a8af-af2ef3a5cdb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>banner-articler</value>
      <webElementGuid>a90c81f1-750b-4a4c-9c11-3b4abd1a3c61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://a.m.dana.id/promo/gamespage/Web-Banner-Article-Game.png</value>
      <webElementGuid>2556053a-fbd4-4540-9bc0-7a9acf296b39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;item-digital&quot;]/section[1]/div[@class=&quot;news-event-home l-desktop&quot;]/div[@class=&quot;carousel-container&quot;]/div[@class=&quot;news-carousel&quot;]/div[@class=&quot;glide glide--ltr glide--slider glide--swipeable&quot;]/div[@class=&quot;glide__track&quot;]/ul[@class=&quot;glide__slides&quot;]/div[@class=&quot;glide__slide glide__slide--active&quot;]/div[1]/div[@class=&quot;news-carousel-card f-flex f-justify-space-between l-desktop&quot;]/div[@class=&quot;news-carousel-card__img-container&quot;]/img[1]</value>
      <webElementGuid>13827e91-867d-4adb-a7b9-6d838863ca65</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/section/div/div/div/div/div/ul/div/div/div/div/img</value>
      <webElementGuid>224e70d6-c99e-4f8a-b5cf-830d37c9dcb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='banner-articler']</value>
      <webElementGuid>cbf4e6c4-2888-4abf-ac28-94582df00364</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>5b611ccc-faae-46e8-9c74-da3f8a3ea205</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'banner-articler' and @src = 'https://a.m.dana.id/promo/gamespage/Web-Banner-Article-Game.png']</value>
      <webElementGuid>67fcdbe6-9df6-493e-9044-47912f277ead</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
