<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_promocarousel</name>
   <tag></tag>
   <elementGuidId>7e10abea-5ca1-4521-8138-838ccef37e52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div/section/div/div/div[6]/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.swiper-slide.swiper-slide-prev > div.promo-hero__container > img[alt=&quot;Beli Voucher Alfamart di Dana Deals  Belanja Makin Irit Di Merchant Favorit! &quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4a48dc21-000a-421c-ad11-cf42844fbc36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>a9f51b3a-e209-4d27-b209-e01ab33184ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Beli Voucher Alfamart di Dana Deals  Belanja Makin Irit Di Merchant Favorit! </value>
      <webElementGuid>2d05dd3a-4b05-4fe9-8f1a-f819b6a20cbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//a.m.dana.id/danaweb/promo/1684776745-1683620617-Cover---DANA-Deals__1_.png</value>
      <webElementGuid>f7b97adb-da58-44a4-bfee-ce800b8ae2d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[1]/div[@class=&quot;promo-page&quot;]/section[@class=&quot;promo-hero&quot;]/div[@class=&quot;swiper-container swiper-container-fade swiper-container-initialized swiper-container-horizontal&quot;]/div[@class=&quot;swiper-wrapper&quot;]/div[@class=&quot;swiper-slide swiper-slide-prev&quot;]/div[@class=&quot;promo-hero__container&quot;]/img[1]</value>
      <webElementGuid>012f3027-a4a6-44dc-a756-7afe553938ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div/section/div/div/div[6]/div/img</value>
      <webElementGuid>fb353297-b314-4f59-9360-503afcfad892</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Beli Voucher Alfamart di Dana Deals  Belanja Makin Irit Di Merchant Favorit! '])[2]</value>
      <webElementGuid>6c8fcee3-91c8-45b4-a69b-e878ef635790</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/img</value>
      <webElementGuid>6a41bd97-b827-4de5-8d7d-9b531182441e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Beli Voucher Alfamart di Dana Deals  Belanja Makin Irit Di Merchant Favorit! ' and @src = '//a.m.dana.id/danaweb/promo/1684776745-1683620617-Cover---DANA-Deals__1_.png']</value>
      <webElementGuid>f0602908-8b6c-4ba1-aa83-42689e76f019</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
