<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_glide</name>
   <tag></tag>
   <elementGuidId>396e3b21-8a88-414b-b4d3-047a3eecf4d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div[2]/div/div/div/div/ul/img[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.glide__slide.glide__slide--active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>96c0c4d1-a013-4d28-bfc7-6c42de243477</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://a.m.dana.id/promo/gamespage/GPV-IAP-MLBB-Maret_Games-Banner.png</value>
      <webElementGuid>a3780d6a-138e-4973-8d4b-74a48fb45fbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>banner-img</value>
      <webElementGuid>040f17a4-8584-4718-b671-17b442f45b10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>glide__slide glide__slide--active</value>
      <webElementGuid>640282d4-74dc-4802-99bf-7a94a25d5dc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;item-digital&quot;]/div[@class=&quot;item-digital-home&quot;]/div[@class=&quot;item-digital-home__content l-desktop&quot;]/div[@class=&quot;home-banner-container&quot;]/div[@class=&quot;home-banner-game-carousel&quot;]/div[@class=&quot;glide glide--ltr glide--carousel glide--swipeable&quot;]/div[@class=&quot;glide__track&quot;]/ul[@class=&quot;glide__slides&quot;]/img[@class=&quot;glide__slide glide__slide--active&quot;]</value>
      <webElementGuid>f07048dc-345c-46d1-8f6b-53de4d67e78d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div/div/div/div/ul/img[2]</value>
      <webElementGuid>cebc8e0d-b8fa-4cbe-a9c1-287cad562d0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='banner-img'])[2]</value>
      <webElementGuid>30de2258-87cb-407a-9421-a1985e55d7f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img[2]</value>
      <webElementGuid>efcefbdd-de2a-4e84-b94d-5ef5b67e5026</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://a.m.dana.id/promo/gamespage/GPV-IAP-MLBB-Maret_Games-Banner.png' and @alt = 'banner-img']</value>
      <webElementGuid>788766c8-e04c-4573-b3b7-4d81cffccc4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
