<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_text</name>
   <tag></tag>
   <elementGuidId>6af9ce95-64de-4559-826d-c79b157335f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[type=&quot;text&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>47b624bb-75cf-47d1-be2b-78e9ab4157b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>e7b20c05-a185-4b1a-a744-6fc07502332c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Looking for apps or games?</value>
      <webElementGuid>7d2caca7-6162-4f59-816c-49ed20430e76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9d7df5ae-1e3e-487d-bb8e-5f1e822a74bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;item-digital&quot;]/div[1]/div[@class=&quot;navbar&quot;]/div[@class=&quot;f-tab f-tab--white f-tab--fixed bgTabs f-flex f-align-center f-justify-space-between&quot;]/div[@class=&quot;right&quot;]/div[1]/div[@class=&quot;provider-search&quot;]/form[1]/div[@class=&quot;f-input txtSearchProviderName&quot;]/label[@class=&quot;f-input__text-box f-input--focus f-input__text-box--padding f-input__unit&quot;]/div[@class=&quot;f-input__container&quot;]/div[@class=&quot;f-input__wrapper&quot;]/div[@class=&quot;f-input__input-slot&quot;]/input[1]</value>
      <webElementGuid>fd66e3b9-48d7-418a-aca6-8f063ecbffdb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='text']</value>
      <webElementGuid>7b91e400-2c5e-4699-8b6a-5c49efaec069</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div/div[3]/div/div/form/div/label/div/div/div[2]/input</value>
      <webElementGuid>81a6be0d-c864-4773-8abc-4d4f8ae4ed54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>b65a8c14-841d-4099-8dea-ce626b4c52d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Looking for apps or games?' and @type = 'text']</value>
      <webElementGuid>10365eac-33eb-43d7-8212-73e68c35cab8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
