<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Home</name>
   <tag></tag>
   <elementGuidId>eb8adc33-f0ad-42c5-9108-57585eaead07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[(text() = 'Home' or . = 'Home')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.p-16</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b58085a9-c138-4aed-bc9d-fb14b29d70c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-16</value>
      <webElementGuid>92d08040-042e-4262-8534-6730333c2c21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Home</value>
      <webElementGuid>5d3865aa-64ba-46d5-9b67-760f15c042fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;item-digital&quot;]/div[1]/div[@class=&quot;navbar&quot;]/div[@class=&quot;f-tab f-tab--white f-tab--fixed bgTabs f-flex f-align-center f-justify-space-between&quot;]/div[@class=&quot;center f-flex f-align-center&quot;]/div[@class=&quot;f-title title-16 text-white tab-wrapper active&quot;]/span[@class=&quot;p-16&quot;]</value>
      <webElementGuid>037ee052-9efb-4900-831a-46b9fecc3761</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div/div[2]/div/span</value>
      <webElementGuid>fe3bbddb-590d-4b1f-bbb0-3986db883c0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Games'])[1]/preceding::span[1]</value>
      <webElementGuid>5520e709-9c7a-44f4-b5c3-cb5ff5a24e6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Digital Voucher'])[1]/preceding::span[2]</value>
      <webElementGuid>7e309d46-7a37-4b44-abe8-d2d97712c684</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Home']/parent::*</value>
      <webElementGuid>c110de04-5483-45fd-b17c-c0875517f35e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span</value>
      <webElementGuid>a21fb021-e594-4852-ae12-12786309cc50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Home' or . = 'Home')]</value>
      <webElementGuid>2911f133-3615-4f88-afb9-9a9656474ef7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
