<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tag_dana</name>
   <tag></tag>
   <elementGuidId>30a9707a-7d4a-4387-887c-213dcec15dc7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='#BEBASDRAMA']/parent::*</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.home-hero__tagline</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>9f1b2c2f-02ae-4f0f-a71a-5f8a6161636e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>home-hero__tagline</value>
      <webElementGuid>f068b4ac-160c-4528-b2bb-17dac3106eed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
          #BEBASDRAMA
        </value>
      <webElementGuid>d373e64f-2978-4ab7-a1d9-9945bd254fc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[1]/div[@class=&quot;home&quot;]/section[@class=&quot;home-hero&quot;]/div[1]/div[@class=&quot;home-hero__content&quot;]/div[@class=&quot;home-hero__content__text&quot;]/p[@class=&quot;home-hero__tagline&quot;]</value>
      <webElementGuid>347abb63-cc6d-4db3-88e7-79b1f00fe068</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div/section/div/div[2]/div[2]/p</value>
      <webElementGuid>4755c252-5d4a-4508-807e-91c7dc4d0632</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Semua transaksi bisa di satu dompet digital'])[1]/following::p[1]</value>
      <webElementGuid>b09106f4-203b-42f5-8d91-33d4f551cee7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download'])[1]/following::p[1]</value>
      <webElementGuid>890fa7d1-7453-4ac7-a548-34ecd6e5e5bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tentang DANA'])[1]/preceding::p[1]</value>
      <webElementGuid>cefa8915-060e-4e6f-9bb1-125e2b9e9383</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Temukan Caranya'])[1]/preceding::p[1]</value>
      <webElementGuid>db37b0bb-e6dd-4a82-bba5-6be45bf614d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='#BEBASDRAMA']/parent::*</value>
      <webElementGuid>ed8162ea-aa6e-4f8e-a8ef-f1ee406a5399</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>66eec7fd-6067-4595-8a21-f2c3fb4a6962</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '
          #BEBASDRAMA
        ' or . = '
          #BEBASDRAMA
        ')]</value>
      <webElementGuid>b42a2ac7-880f-483d-ae6e-2282aef0576a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
